title: 'Взлет Новосибирск'
default_lang: ru
author:
  name: Denis
  email: den.zakh@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Официальный представитель компании Взлет в Новосибирске. Продажа приборов учета расхода жидкостей, газа и тепловой энергии.'
  0: 'взлет, приборы учета'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
